### PR TITLE
add a xapi plugin that lists the ZFS pools on the host.

### PR DESCRIPTION
**Pull request by nraynaud**
this is the prelude to this PR: https://github.com/vatesfr/xen-orchestra/pull/4258

### CODE REVIEW

**Comment by stormi** [comment]
Would the plugins system in XAPI let us have our plugins share common methods (logging, error handling...)?

**Comment by nraynaud** [comment]
at least we can create a shared python lib, I didn't know how much I should change existing code tho.

**Comment by stormi** [comment]
> at least we can create a shared python lib, I didn't know how much I should change existing code tho.

Since we're in beta stage, it's a good time to allow ourselves to move some code around.

**Comment by stormi** [comment]
Looks good. Do you want to squash the commits into one yourself, or let me do it while merging?

**Comment by nraynaud** [comment]
you can do it, git is a struggle for me.

**Comment by stormi** [comment]
Forgot to close this one. It is merged already.

**Pull request closed without merging**
